### ISSUE TITLE
todo

### ISSUE THREAD

**Issue by jasoneppink** [jasoneppink/raspberry-pi-external-subtitles#1]
- [x] create bash script to run at boot (based on [FluxVision startup.sh](https://github.com/jasoneppink/FluxVision/blob/master/startup.sh))
- [x] create dashboard script that replaces /etc/motd with relevant info (based on [FluxVision dashboard.py](https://github.com/jasoneppink/FluxVision/blob/master/dashboard.py))
- [x] design/fix [where language is placed on screen when switching languages](https://github.com/jasoneppink/extsub/blob/master/extsub.ino#L69)
- [x] create config file with following options using ConfigParser:
  - [x] title of video
  - [x] default language
  - [x] video filename (local to extsub.py)
  - [x] subtitle files directory (local to extsub.py)
  - [x] if LCD display launches (1) running subtitles in default language, (2) blank, or (3) with customizable text (e.g. "Press Button for Captions")
  - [x] if LCD display defaults to blank screen or customizable text, an "off/cancel" option allows the user who is cycling through languages to return to that default screen (blank or customizable text) rather than see subtitles
  - [x] if LCD display defaults to blank screen customizable text, determine if the display reverts to default screen (1) at end of video playback, (2) after returning to the same timecode when button was pressed, or (3) if it completes one full play through to the end (hits the end twice)
    - [x] reset to default language font if displaying customizable text
